[project]
name = "spareroom-kata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.121.1",
    "httpx>=0.28.1",
    "pytest>=9.0.0",
    "pytest-asyncio>=0.23.3",
    "requests>=2.32.5",
]
